- id: black
  name: black
  description: "Black: The uncompromising Python code formatter"
  entry: black
  language: system
  require_serial: true
  types: [python]
- id: pylint
  name: pylint
  entry: pylint
  language: system
  types: [python]
  require_serial: true
